version: '3'
services:
  db_test:
    image: postgres_db
  web:
    build: ./
  mqtt:
    image: eclipse-mosquitto:latest
  nginx:
    image: nginx:latest
  web_test:
    build:
      context: .
      dockerfile: ./tests/Dockerfile
