service: iot-cloud

provider:
  name: openwhisk
  runtime: python

functions:
  hello:
    handler: src/handler.hello
    runtime: python
    image: martinheinz/python3action-iotcloud:latest
    timeout: 10

package:
  include:
    - src/**
  exclude:
    - .gitignore
    - credentials.csv
    - LICENSE
    - Makefile
    - MANIFEST.in
    - pylintrc
    - README.rst
    - requirements.txt
    - serverless.yml
    - setup.py
    - venv/**
    - tests/**
    - .serverless/**
    - docs/**
    - pytest_cache/**

plugins:
  - serverless-openwhisk
